### ISSUE TITLE
Error with Completion Detection

### ISSUE THREAD

**Issue by AndreaBeth11** [clifford-fra/GoogleRecaptchav2#1]
I am having trouble getting this to work (likely an error on my part, but not sure how to resolve).  I followed directions for setup (which were pretty straight forward) and have a reCaptcha on a Flow in my Community that should create a case.  I click the checkbox and submit & get an error saying to complete the captcha.
I left defaults in place, except for the Site & Secret keys.  Any thoughts on how to troubleshoot?

**Comment by clifford-fra** [comment]
Hey,

does the recaptcha Challenge window resize properly?
Do you use a custom URL for your community?

First, you should try to insert your community domain in the `Origin Page URL (optional)` input variable.

**Comment by clifford-fra** [comment]
Hi AndreaBeth11,

i debugged a bit and saw the error:

Your community (guest) user needs the permission to access the `GoogleRecaptchaHandler `class. This will most probably solve your problem. This security requirement came with one of the past Salesforce updates.

Best regards
Clifford

**Comment by AndreaBeth11** [comment]
The access to the class worked and I can submit the case.  (Albeit now I get a Flow error, but that's not to be dealt with here)
